import UIKit

class LoveBotView: UIView {
    
    // MARK: - Body Parts (Generated by Code)
    let bodyImage = UIImageView(image: BotAssets.body)
    let leftHand = UIImageView(image: BotAssets.hand)
    let rightHand = UIImageView(image: BotAssets.hand)
    let leftFoot = UIImageView(image: BotAssets.foot)
    let rightFoot = UIImageView(image: BotAssets.foot)
    
    // MARK: - Limbs (The "Connectors")
    private var leftArm: RubberLimbView!
    private var rightArm: RubberLimbView!
    private var leftLeg: RubberLimbView!
    private var rightLeg: RubberLimbView!
    
    // MARK: - Physics Engine
    private var animator: UIDynamicAnimator?
    private var gravity: UIGravityBehavior?
    private var collision: UICollisionBehavior?
    private var bodyBehavior: UIDynamicItemBehavior?
    
    // State
    private var isFalling = false
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        setupPuppet()
    }
    
    required init?(coder: NSCoder) {
        super.init(coder: coder)
        setupPuppet()
    }
    
    private func setupPuppet() {
        self.backgroundColor = .clear
        
        // 1. Configure and Add Body Parts
        setupPart(bodyImage, size: CGSize(width: 60, height: 60))
//        setupPart(leftHand, size: CGSize(width: 12, height: 12))  // Slightly bigger hands
//        setupPart(rightHand, size: CGSize(width: 12, height: 12))
        setupPart(leftFoot, size: CGSize(width: 20, height: 14))
        setupPart(rightFoot, size: CGSize(width: 20, height: 14))
        
        // Initial Position (Before physics starts)
        resetPosition()
        
        // 2. Create the Rubber Limbs (Code-drawn lines)
//        leftArm = createLimb(from: bodyImage, to: leftHand, direction: .left)
//        rightArm = createLimb(from: bodyImage, to: rightHand, direction: .right)
        leftLeg = createLimb(from: bodyImage, to: leftFoot, direction: .left)
        rightLeg = createLimb(from: bodyImage, to: rightFoot, direction: .right)
    }
    
    private func setupPart(_ view: UIView, size: CGSize) {
        view.frame.size = size
        // Fallback if image fails
        if (view as? UIImageView)?.image == nil {
            view.backgroundColor = .black
            view.layer.cornerRadius = size.width / 2
        }
        addSubview(view)
    }
    
    private func createLimb(from start: UIView, to end: UIView, direction: RubberLimbView.BendDirection) -> RubberLimbView {
        let limb = RubberLimbView(frame: bounds)
        limb.startView = start
        limb.endView = end
        limb.bendDirection = direction
        
        // Matches the Deep Grape outline color
        limb.limbColor = BotAssets.strokeColor
        limb.limbWidth = BotAssets.strokeWidth
        
        // UPDATED: Longer arms
        limb.naturalLength = 25
        
        insertSubview(limb, at: 0) // Draw behind body
        return limb
    }
    
    // MARK: - Positioning
    func resetPosition() {
        // Place the bot in the top-right corner (peeking)
        let startX = self.bounds.width - 80
        let startY: CGFloat = 100
        
        bodyImage.center = CGPoint(x: startX, y: startY)
        
        // UPDATED: Hands are now 40px away (was 25)
        leftHand.center = CGPoint(x: startX - 35, y: startY + 15)
        rightHand.center = CGPoint(x: startX + 35, y: startY + 15)
        
        // Feet positions
        leftFoot.center = CGPoint(x: startX - 15, y: startY + 35)
        rightFoot.center = CGPoint(x: startX + 15, y: startY + 35)
        
        // Reset rotation
        bodyImage.transform = .identity
    }
    
    // MARK: - Physics Actions
    func dropAndCrash() {
        guard !isFalling else { return }
        isFalling = true
        
        // 1. Init Animator
        animator = UIDynamicAnimator(referenceView: self)
        
        // 2. Define Physics Items
        let allParts = [bodyImage, leftHand, rightHand, leftFoot, rightFoot]
        
        // 3. Gravity
        gravity = UIGravityBehavior(items: allParts)
        gravity?.magnitude = 2.5 // Heavy fall
        animator?.addBehavior(gravity!)
        
        // 4. Collision (Floor and Walls)
        collision = UICollisionBehavior(items: allParts)
        collision?.translatesReferenceBoundsIntoBoundary = true
        animator?.addBehavior(collision!)
        
        // 5. Ragdoll Connections
        // UPDATED: Shoulders are wider (30) so arms don't clip
        addJoint(body: bodyImage, limb: leftHand, offsetX: -30, offsetY: 0)
        addJoint(body: bodyImage, limb: rightHand, offsetX: 30, offsetY: 0)
        addJoint(body: bodyImage, limb: leftFoot, offsetX: -10, offsetY: 30)
        addJoint(body: bodyImage, limb: rightFoot, offsetX: 10, offsetY: 30)
        
        // 6. Bounciness & Friction
        bodyBehavior = UIDynamicItemBehavior(items: allParts)
        bodyBehavior?.elasticity = 0.4 // Bouncy
        bodyBehavior?.friction = 0.5
        bodyBehavior?.angularResistance = 0.5
        animator?.addBehavior(bodyBehavior!)
        
        // 7. Spin
        let push = UIPushBehavior(items: [bodyImage], mode: .instantaneous)
        push.pushDirection = CGVector(dx: -0.5, dy: 0)
        animator?.addBehavior(push)
    }
    
    private func addJoint(body: UIView, limb: UIView, offsetX: CGFloat, offsetY: CGFloat) {
        
        let joint = UIAttachmentBehavior(
            item: limb,
            offsetFromCenter: .zero,
            attachedTo: body,
            offsetFromCenter: UIOffset(horizontal: offsetX, vertical: offsetY)
        )
        
        // UPDATED: Rope is longer (35)
        joint.length = 35
        joint.damping = 0.3
        joint.frequency = 3.0
        
        animator?.addBehavior(joint)
    }
    
    func recoverAndStandUp() {
        animator?.removeAllBehaviors()
        animator = nil
        isFalling = false
        
        UIView.animate(withDuration: 0.8, delay: 0, usingSpringWithDamping: 0.6, initialSpringVelocity: 0.5, options: [], animations: {
            self.resetPosition()
        }, completion: nil)
    }
}
