import Foundation
import UIKit
import Supabase

/// Handles uploading a memory image to Supabase Storage as a temporary relay,
/// then inserting the metadata row. The image is already saved locally before
/// this manager is called, so `fileName` is passed in (pre-generated by the VC).
final class MemoryUploadManager {
    static let shared = MemoryUploadManager()
    private let supabase = SupabaseManager.shared.client
    private init() {}

    // MARK: - Public

    func uploadMemory(
        memoryId: UUID,           // caller-generated — must match the local Memory.id
        userId: String,
        relationshipId: UUID,
        imageData: Data,
        title: String,
        description: String,
        isoDate: String,
        fileName: String
    ) {
        var backgroundTaskID: UIBackgroundTaskIdentifier = .invalid
        backgroundTaskID = UIApplication.shared.beginBackgroundTask(withName: "MemoryUpload") {
            UIApplication.shared.endBackgroundTask(backgroundTaskID)
            backgroundTaskID = .invalid
        }

        Task {
            do {
                // ── Step 1: Upload image to Supabase Storage (temp relay) ───────
                try await supabase.storage
                    .from("memory-images")
                    .upload(path: fileName, file: imageData)

                // ── Step 2: Insert metadata row (is_synced starts as false) ─────
                try await supabase
                    .from("memories")
                    .insert([
                        [
                            "memory_id":       memoryId.uuidString,
                            "relationship_id": relationshipId.uuidString,
                            "user_id":         userId,
                            "title":           title,
                            "description":     description,
                            "image_path":      fileName,
                            "memory_date":     isoDate,
                            "is_synced":       "false"
                        ]
                    ])
                    .execute()

                // ── Step 3: Notify partner ─────────────────────────────────────
                try? await NotificationService.shared.sendPartnerNotification(
                    relationshipId: relationshipId,
                    type: "memory_added",
                    message: "Your partner just added a new memory. Click to reveal!",
                    entityType: "memory",
                    entityId: memoryId.uuidString
                )

            } catch {
                print("[MemoryUploadManager] upload failed: \(error)")
            }

            if backgroundTaskID != .invalid {
                UIApplication.shared.endBackgroundTask(backgroundTaskID)
                backgroundTaskID = .invalid
            }
        }
    }
}
